{ "creds": { "noiseKey": { "private": { "type": "Buffer", "data": "oBKLLRhWnsmEwvagvTj3zBpCMtrPd+9LH/xwaAMSYE4=" }, "public": { "type": "Buffer", "data": "+wPWNmPaAH60YEzfX9dEipgQxTUN7aZtbi5fJvrOvBA=" } }, "signedIdentityKey": { "private": { "type": "Buffer", "data": "YCw1/Vi4mim/BC9ZKuhEB9+fcTbUQC5QrbKgO479MEE=" }, "public": { "type": "Buffer", "data": "mj2Y/p+BDcsrC1n8+DUYWePiVaplTYQmkYLpGmj9g38=" } }, "signedPreKey": { "keyPair": { "private": { "type": "Buffer", "data": "oP0Yj6AZof0nt/sr3QnKlgN1uCILcle2nLQoW+AaNHk=" }, "public": { "type": "Buffer", "data": "lZ4vAGIFnC89oCzABwlW2IoFe0Rb8JUt0zJVsRGRBFs=" } }, "signature": { "type": "Buffer", "data": "W/RfM4SYv5eA4G5fQqn4LDfXgx6CQlZAHH/5BTr9srXwO3h/TcSNQpgPaF5tawXDqV/NlngAUDyiSBujH8+qjQ==" }, "keyId": 1 }, "registrationId": 255, "advSecretKey": "NBXrnojrYBurO6YD5XgT/xdrunHPgSvJL7WBzZPUolQ=", "nextPreKeyId": 31, "firstUnuploadedPreKeyId": 31, "serverHasPreKeys": true, "account": { "details": "CLP85dECENzn55oGGAM=", "accountSignatureKey": "mGfmDoN7hIvDBnLZyLCX8e+AsLUi63skhDizimrRHH4=", "accountSignature": "xBMkU2Dc6bEb3ad3J/BRbUdWVxMMPeCY5gCvdn84piS93IsaO5qmVdRDq8l5u4+5i/DIslqS+ofjz0fezJDhCA==", "deviceSignature": "TKTv3eMnV1Apm1Ex5qnBTxby1o9iL9EN1AwNHMZiCSY7FOy3o95y9a01wNUnGPjy5SSaVl8oKR8QyRFQzlaAgg==" }, "me": { "id": "94703739541:5@s.whatsapp.net", "verifiedName": "", "name": "Kaviya bot" }, "signalIdentities": [ { "identifier": { "name": "94703739541:5@s.whatsapp.net", "deviceId": 0 }, "identifierKey": { "type": "Buffer", "data": "BZhn5g6De4SLwwZy2ciwl/HvgLC1Iut7JIQ4s4pq0Rx+" } } ], "lastAccountSyncTimestamp": 1666839518, "myAppStateKeyId": "AAAAAGM1" }, "keys": { "preKeys": { "1": { "private": { "type": "Buffer", "data": "YL6legWo6rFHhtHYV5o8LEz+6To9VdXYL3wY8gOJW0o=" }, "public": { "type": "Buffer", "data": "jhJd9/NIoIKmTZap+2aqF4uNuXU2MQqeG1BkuxvhWgU=" } }, "2": { "private": { "type": "Buffer", "data": "aDlIauILFMWjfZbpp8McrkrRCUrYLPuMouacxmBLv1c=" }, "public": { "type": "Buffer", "data": "uCjr01WfJOUNtq5nH9JHN3IWgCJdL72D8XeTOqn/xUw=" } }, "3": { "private": { "type": "Buffer", "data": "gE8xVUr95KA4VJaY8Ja+11Uo2Gq8juxrSm1zUALfDGQ=" }, "public": { "type": "Buffer", "data": "rSxpkX/8E8e9CrJgZvOlXor0iweMkd+kAOiDJcGXMFg=" } }, "4": { "private": { "type": "Buffer", "data": "wAFJ2OQglnCf87RGmrXs0l0JYZBCDrOK1DAGCHQjyU8=" }, "public": { "type": "Buffer", "data": "5ejstxGHh5/7pJbIKUnFPI6uNNcp7yMC1vpK61WStl4=" } }, "5": { "private": { "type": "Buffer", "data": "eA/6aeYm9RiS2JYJ/bJK76kxKG2kt6P/oIaFaJ36vFo=" }, "public": { "type": "Buffer", "data": "8Y/vdlDL2yMws+byhV4PTRJxIsIoBmiU+Xlno5XsSDw=" } }, "6": { "private": { "type": "Buffer", "data": "GN3YT3hXbnB487Xl3IaEvEuqsCuZU9EP+LjS/g7xR00=" }, "public": { "type": "Buffer", "data": "Ko8HzlpaDFaDiCszsjZYOihUpGhb4vvqaQxgKsfi+wA=" } }, "7": { "private": { "type": "Buffer", "data": "CPrfJUpy9pTsMiqqPjOl5TeZzM/bYMvLAmlf3IKoknM=" }, "public": { "type": "Buffer", "data": "KKmTHuK3M8v56gPgDuL7XKudyWWnqBwHiIwiE5D3Ex8=" } }, "8": { "private": { "type": "Buffer", "data": "iGFIMagfhuUAsBazTwY/g+vmLCukZROdHd2wAa3SJUA=" }, "public": { "type": "Buffer", "data": "PhNywSDyQjo6ebh4teghhw2b1uUwBUfE1SuClgC9p0Q=" } }, "9": { "private": { "type": "Buffer", "data": "oFfOGGSgqIP0QDUDZk5bAgmwAC7eHMcvcTtm0HW+IlM=" }, "public": { "type": "Buffer", "data": "6yTcAKyZEKw8FQMB+A2jBql/9UzgLHPans3jc4UpyWs=" } }, "10": { "private": { "type": "Buffer", "data": "yJUIhxU08j64gagWZFoNUmAlPmoLII5X/yfhTFcn51E=" }, "public": { "type": "Buffer", "data": "8jzGMoMyW4wLnF7c1DxXqzWBragoPZWKVz40UtZOBQ4=" } }, "11": { "private": { "type": "Buffer", "data": "KPyyk0MIyzzr6/KazwLgk1+6SKJKeWkfLmC3u7y0VH4=" }, "public": { "type": "Buffer", "data": "IvfZ8EW8dGzCwUSAaeuPHMjkKE9jMB5DGBgoQqxf2mk=" } }, "12": { "private": { "type": "Buffer", "data": "WJqAVmM57YeBgFZ825SIwSi99LVaEXyLpDGy1DKLpXU=" }, "public": { "type": "Buffer", "data": "t0qhOKYV/cTWXWC1v/totvxEc8RRFZwtFvoHsPYOPhE=" } }, "13": { "private": { "type": "Buffer", "data": "kESjos00D7QjQT78AmUMOQSwN3Va+kcGHFmN8sXUElM=" }, "public": { "type": "Buffer", "data": "lWpRRq5Rcij0RHETgc7UIyxfMg+Vr53juLhHbs7c3XY=" } }, "14": { "private": { "type": "Buffer", "data": "+CwWKfOKuWTt6YzF6zYvdrHYq7+mQpm9tcfhYrtboHY=" }, "public": { "type": "Buffer", "data": "0Io0UZAX5WhU0N8xZIIlFI2sSOLTdYzjL9EM4IwscjA=" } }, "15": { "private": { "type": "Buffer", "data": "8HqUuOPj6y0jpLQ6FP8A+GY104yPzoF+zWZ2nrmsBH0=" }, "public": { "type": "Buffer", "data": "Zdgs+6N6bsWs111pvB6F1lEbO9VLEx0NT8pmRUNE7UY=" } }, "16": { "private": { "type": "Buffer", "data": "IIMV31WfIwT6v/MJumQWUqBDxHDgBeIUZFimqj0uYmU=" }, "public": { "type": "Buffer", "data": "QySgWXfCSUcxSPSDZ0Psoj5s1rQwyBO+052iYMA4bwA=" } }, "17": { "private": { "type": "Buffer", "data": "KKZu3tJ3n1T018RzIEN5XbM2ONUhunvLiPllsquJ+l0=" }, "public": { "type": "Buffer", "data": "eIeC7PsJk0PlV1n1U9U1AKYLzr4pIKBvTkJXvhPZ2gk=" } }, "18": { "private": { "type": "Buffer", "data": "KCPjtqAyK4iAPb3Q0PdT8B5l+ZQr0Ou7rlApH+ymF0w=" }, "public": { "type": "Buffer", "data": "PEU/1eI+rfOcRTsHse62Z9F8xEB661+Y9nNSuhSiiGs=" } }, "19": { "private": { "type": "Buffer", "data": "UIvEyyDpZQMNxkVRm4wIDq0NgPYaftW1DW+AQw7HRUE=" }, "public": { "type": "Buffer", "data": "CJfWgPaHCzMiEBp63NG7bYSs5kKAX2IWKRkXzOTXmH8=" } }, "20": { "private": { "type": "Buffer", "data": "yOLPEWHDLvaTkYEiIteS28cyUrl4BmwEDFVfuWqsLF0=" }, "public": { "type": "Buffer", "data": "c0Gjd+6KUgFH/dH94AUFZScGU6O5CLmjQ8fiXI4rNWU=" } }, "21": { "private": { "type": "Buffer", "data": "OJq6yoAtTmuufghu2U4yjdlED53wdINFRzisHldBPFs=" }, "public": { "type": "Buffer", "data": "DVZIvZLlD1zzAoFPUVM9U65kKoWZJCOuaQwJsVcrXQA=" } }, "22": null, "23": { "private": { "type": "Buffer", "data": "yGMVJVQISuVpoSMjEItG6hFb01hjVN2hDiqh+ddEAkI=" }, "public": { "type": "Buffer", "data": "QWJQSZrng16OHmvC10SXR1Pu2LN1Zwc8COEEMJBcFQY=" } }, "24": { "private": { "type": "Buffer", "data": "+CtNfpkLa9LGrO3k9NAItRSx9/lh9vd5OxvzE7wcInc=" }, "public": { "type": "Buffer", "data": "DWbM7YoD0dKHMwcq7dBQljsQz406gVk94/EeS5yMFhM=" } }, "25": { "private": { "type": "Buffer", "data": "oG2yaP7l561fS6gdOI1zZO7jyks4VILzMa4UK5GfaUM=" }, "public": { "type": "Buffer", "data": "Cs8HKK7BUd09CbPUGCuY+QevTG1TmzPMCH0rUmO7OG4=" } }, "26": { "private": { "type": "Buffer", "data": "WKi78HgsIGesa2kIqfBkK1VMbPRmiiy5oc8L0XsT3Ek=" }, "public": { "type": "Buffer", "data": "336NYtT/aCoAUTHjb0yxJX3WGaLKb1olPtA+ssbrdxU=" } }, "27": { "private": { "type": "Buffer", "data": "4NklWT4XtUfKxDzs/3nBwU59vLXGAvFZaLd7tiJe1mQ=" }, "public": { "type": "Buffer", "data": "XdnX4aG4a0WgItKXOsbLQp5qczpt/NKk5BcnoiVHEVs=" } }, "28": { "private": { "type": "Buffer", "data": "gF+OgqDBEoIotXOJqrKnh+8w0jFGqMiwkibwCPUf42M=" }, "public": { "type": "Buffer", "data": "TNR4D7wsCVVB/DgNXRDWDplwrt4QxkeBUG3t/iRQMA8=" } }, "29": { "private": { "type": "Buffer", "data": "CD0b6h8fnwFphmNOSo9fPhRu1XiC+zw4dN3X9bnnQ20=" }, "public": { "type": "Buffer", "data": "AbVpS1Ho3xCMqxaltoaXXX1c4CBp9CGv3lIjstd9rzU=" } }, "30": { "private": { "type": "Buffer", "data": "CJ2jWHsifp7P7eJIUA2dz38mlnYJPEM3hOiTfcARxEw=" }, "public": { "type": "Buffer", "data": "M4RES/XM7F223/io7c/vJMmO96y8h8n3f1w0YcGcBAI=" } } }, "sessions": { "94703739541.0": { "_sessions": { "BQFL9MhfUeOpOd2eCs3FhBUdyL7Kdv/d6gbvwu0+1LZr": { "registrationId": 423293513, "currentRatchet": { "ephemeralKeyPair": { "pubKey": "Bd2v5w2Q8Nlej3C+Q/7wizBTqr84u6h55EsaAImQIQcn", "privKey": "wDq7S4YcgNgSVMqvP/53qfVLessHAR2LOeXAvq+pjlw=" }, "lastRemoteEphemeralKey": "BbHdKVSg9GS7ddAdZ6T8UlGshk0KbhYKRT44qj7hpztZ", "previousCounter": 0, "rootKey": "X3+Ts82NkqC8cfUsp0GahkHIQWSrh5tU+95McPPuWJ4=" }, "indexInfo": { "baseKey": "BQFL9MhfUeOpOd2eCs3FhBUdyL7Kdv/d6gbvwu0+1LZr", "baseKeyType": 2, "closed": -1, "used": 1666839519089, "created": 1666839519089, "remoteIdentityKey": "BZhn5g6De4SLwwZy2ciwl/HvgLC1Iut7JIQ4s4pq0Rx+" }, "_chains": { "BbHdKVSg9GS7ddAdZ6T8UlGshk0KbhYKRT44qj7hpztZ": { "chainKey": { "counter": 7, "key": "ZmRf+pgWz1NWBt7uPB44Dl93W5XZtXbHwYgqpBUvr5I=" }, "chainType": 2, "messageKeys": {} }, "Bd2v5w2Q8Nlej3C+Q/7wizBTqr84u6h55EsaAImQIQcn": { "chainKey": { "counter": -1, "key": "fqTo9mfbvt98SDWWCgClJSH1K1KTQ3ypYkqcs01kbZ8=" }, "chainType": 1, "messageKeys": {} } } } }, "version": "v1" } }, "appStateSyncKeys": { "AAAAAGM0": { "keyData": "R7Axqjoi1WaRYOLkhq6K5d14hVjeZ5eBglXYm9I/q1c=", "fingerprint": { "rawId": 708410931, "currentIndex": 1, "deviceIndexes": [ 0, 1 ] }, "timestamp": "1666838465012" }, "AAAAAGMy": { "keyData": "MQx28I8Jtcxb+4o9uCoiMRZyRyJbOR9XWyTRzJ1/cU4=", "fingerprint": { "rawId": 708410929, "currentIndex": 1, "deviceIndexes": [ 0, 1 ] }, "timestamp": "0" }, "AAAAAGMz": { "keyData": "d9wa1jQf0mVLlwfy0pK726+77Jp8TdHJdMozeVAftP8=", "fingerprint": { "rawId": 708410930, "currentIndex": 1, "deviceIndexes": [ 0 ] }, "timestamp": "1666837752055" }, "AAAAAGMx": { "keyData": "7QiH6grQ15cEbbZImsZrNjdcQKV15zCj0ZcWVxFvcTI=", "fingerprint": { "rawId": 708410928, "currentIndex": 1, "deviceIndexes": [ 0, 1 ] }, "timestamp": "0" }, "AAAAAGM1": { "keyData": "AFvNQgfelXH8DxJA8bYfKGR2DTIfT6Mk0EflxNd1feg=", "fingerprint": { "rawId": 708410931, "currentIndex": 3, "deviceIndexes": [ 0, 1, 3 ] }, "timestamp": "1666839524679" } }, "appStateVersions": { "critical_block": { "version": 5, "hash": { "type": "Buffer", "data": "oD/GrNd/++rUKMHFO9JRzIJcSm1mrjAayd2iSiHHZJIIbcA/rtF8h4328bHTSYQ+EWeWUg5jZU8Z4t2/O11HQecPFl6v13+VQU93EctWYtry0DiwHkkh/pJNfykyoLjMnBpLR+LAjzopFpzZZSYQF1misG5pZGOP4RqGaufBj2k=" }, "indexValueMap": { "g0VqZH38hKhG8bTQaHwWQradBnTlGjW1VdqQnsJk/aE=": { "valueMac": { "type": "Buffer", "data": "cpdRuObyrPhNpbkWZbMlg4BDbZf/w5KTPfDO8r90y8g=" } }, "jNNOf9br8Wtkrz+xe6jaOvgEzUjdZfB/AAFrezbqAqc=": { "valueMac": { "type": "Buffer", "data": "Bt4lJCqO5m28hx3bywFXgSL2TeMuV/YbJkv9hRJ1sy4=" } }, "APxyEDTNEDbo2ImOja+IRCAtc3+XiybMyBc4mo00oTc=": { "valueMac": { "type": "Buffer", "data": "OIOlmrRFFOmLOwLNZ45wWz7KfxSiToCoCvbmk3PZPbw=" } } } } } } }
























































